---
- name: Create user and copy files into users home dir
  hosts: all
  tasks:
    - name: Create user
      user:
        name: Ravi
        password: intelliqit
        home: /tmp/Ravi
        uid: 9090
        comment: "A super user"
    - name: Copy file into users home dir
      copy:
        src: /home/ubuntu/tomcat-users.xml
        dest: /tmp/Ravi
        owner: Ravi
        group: Anusha
        mode: 0750
...
